# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlbId', models.CharField(default=b'', max_length=128)),
                ('usTeam', models.CharField(default=b'Tigers', max_length=64)),
                ('themTeam', models.CharField(max_length=64)),
                ('usScore', models.IntegerField(default=0)),
                ('themScore', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('currentStatus', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
    ]
